### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by millionart** [nylas-mail-lives/nylas-mail#210] opened 2018-06-17 23:42 UTC
Uncaught Exception:
Error: The module '/Applications/Nylas Mail.app/Contents/Resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/nslog/lib/nslog.js:15:4)

----

Can't start app.

**Comment by seesemichaelj** [comment] 2018-06-18 01:08
Duplicate of #204

**Closed as completed by seesemichaelj** 2018-06-18 01:08 UTC
