### ISSUE TITLE
2 step verification

### ISSUE THREAD

**Issue by realOgenki** [nylas-mail-lives/nylas-mail#171] opened 2017-11-15 09:13 UTC
Hi,
¿how can I use nylas-mail-lives with my 2 step verification gmail account?
Thanks

**Comment by seesemichaelj** [comment] 2017-11-15 14:22
If you use the Gmail (not IMAP) option when adding an account, you'll be directed to sign in via Google. Google will ask for your 2FA there.

With IMAP, you have to setup an application password which doesn't need the 2FA, but I'm not sure if that's available for all Gmail accounts or just for business.

**Comment by realOgenki** [comment] 2017-11-15 15:44
Thanks Mike. I´m using Gmail option (Inbox) and I was redirected to sign in via Google, but later it can´t connect with my email account on nylas.

**Comment by seesemichaelj** [comment] 2017-11-15 16:07
Can you take a screenshot? Does the browser window say you're good to go, and Nylas looks like it's still trying to connect? I think there was a related issue #153, but we're not sure what the issue is

**Comment by realOgenki** [comment] 2017-11-16 09:39
![nylas1](https://user-images.githubusercontent.com/33685025/32884338-51b9b486-caba-11e7-8be4-75cd8abbc8f9.jpeg)
![nylas2](https://user-images.githubusercontent.com/33685025/32884339-51d67904-caba-11e7-8070-ea7c9b5b1b34.jpg)
![nylas3](https://user-images.githubusercontent.com/33685025/32884340-51f3709a-caba-11e7-8373-a9c046cc9547.jpg)
![nylas4](https://user-images.githubusercontent.com/33685025/32884341-520f3974-caba-11e7-8b41-56ac4f9dfa4f.jpeg)
![nylas5](https://user-images.githubusercontent.com/33685025/32884342-522c6b0c-caba-11e7-8b18-9497c9a06f84.jpeg)
![nylas6](https://user-images.githubusercontent.com/33685025/32884343-52491c34-caba-11e7-8824-0fa7c46f35f2.jpg)

**Comment by fannarsh** [comment] 2017-11-26 03:19
@realOgenki Which OS are you running?
If it's Linux then this issue could be related https://github.com/nylas-mail-lives/nylas-mail/issues/51

**Comment by realOgenki** [comment] 2017-11-27 08:41
Hi @fannarsh, I am using Arch Linux and I have compiled the source code of nylas-mail-lives from AUR, but I am thinking about using .deb file in my Ubuntu or KDEneon distributions...

**Comment by seesemichaelj** [comment] 2017-12-13 04:53
I'm thinking this is a duplicate of #51. If that issue gets resolve, and this is still a problem we can reopen this issue.

**Closed by seesemichaelj** 2017-12-13 04:53 UTC
Labels: Type: Question
