### ISSUE TITLE
Increasing font size for HI-DPI monitors

### ISSUE THREAD

**Issue by thertz** [nylas-mail-lives/nylas-mail#178] opened 2017-11-27 22:01 UTC
There is currently no option to increase font sizes and on high res screens fonts of the main window are too small. Found a way to define a parmeter in the config.json file called "interfaceZoom" which does increase fonts on startup of the app. However, after clicking on any message, font size reverts to the original font size. This is an issue that is resolved in Mailsping b.t.w so probably not too hard to fix.

Ideally, one should be able to choose font size in the preferences - this is a crucial feature for anyone with a high-resolution screen.

**Comment by nirmit** [comment] 2017-11-27 23:22
Hi @thertz, this is a duplicate of #59 and there is a pull request open with the fix.  Its currently being tested/reviewed.

**Comment by thertz** [comment] 2017-11-28 08:20
Thanks. much appreciated. Moving from a mac to linux after many years and Nylas mail seems like a critical component.

**Closed** 2017-11-28 18:20 UTC
Labels: Type: Duplicate
