### ISSUE TITLE
Plugins not loading / not visible in settings

### ISSUE THREAD

**Issue by akshay7394** [nylas-mail-lives/nylas-mail#165] opened 2017-11-11 07:27 UTC
I thought that Mail Merge from the new update wasn't working for whatever reason, but turns out it's a slightly larger problem — no Plugins seem to be showing up on Nylas. I've included a couple of screenshots as well as a copy of my config file (accounts section removed). — from https://github.com/nylas-mail-lives/nylas-mail/pull/144#issuecomment-343645861

I'm running Windows 10, Build 1703; Nylas version 2.2.2 from the Hacktoberfest. 

![screenshot 9](https://user-images.githubusercontent.com/934532/32687324-b2fcfb92-c6df-11e7-887a-2085da9e2753.png)
![screenshot 8](https://user-images.githubusercontent.com/934532/32687325-b3303d2c-c6df-11e7-9322-806f1d77cf14.png)
[config.json.txt](https://github.com/nylas-mail-lives/nylas-mail/files/1463531/config.json.txt)

**Comment by nirmit** [comment] 2017-11-12 05:32
Seems to an issue with `apm`.  @akshay7394 can you look at the errors in the console (Ctrl + Shift + I) when you navigate to the plugins page and provide the error messages here? 

PS:  Remove any sensitive messages in the log! :)

**Comment by seesemichaelj** [comment] 2017-11-12 05:40
Ya this may be related to #75

**Comment by dweremeichik** [comment] 2017-11-12 17:40
This is in fact a duplicate of #75.

**Closed by dweremeichik** 2017-11-12 17:40 UTC
Labels: Type: Duplicate
