### ISSUE TITLE
Failing install 2.2.3 NylasMail.dmg: A javascript error occurred in the main process

### ISSUE THREAD

**Issue by klarani** [nylas-mail-lives/nylas-mail#208] opened 2018-05-12 09:48 UTC
- [x] I have read the above warning completeley

I downloaded the 2.2.3 dmgfile from https://github.com/nylas-mail-lives/nylas-mail/releases/tag/2.2.3 and installed it on my Macbook Pro running 10.12.6 OSX MacOS Sierra. Unfortunalty I cannot copy the text in the error-message.
<img width="424" alt="screen shot 2018-05-12 at 11 43 15" src="https://user-images.githubusercontent.com/7469066/39956068-bb73752e-55d9-11e8-9017-698b461ea265.png">

When I press ok I get no UI at all. Just the Nylas Mail-item in the menu and the option to quit.
I have not tried the other sources.

**Comment by seesemichaelj** [comment] 2018-05-12 15:30
This is a duplicate of #204

**Closed by seesemichaelj** 2018-05-12 15:30 UTC
